import '<redux>/styles/globals.css'
import type { AppProps } from 'next/app'
import Header from '<redux>/components/Header'
import Footer from '<redux>/components/Footer'
import Head from 'next/head'


function App({ Component, pageProps }: AppProps) {
    return (<>
        <Head>
            <title>Frederick Go Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header></Header>
        <Component {...pageProps} />
        <Footer></Footer>
    </>)
}

export default App